apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: neom-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: neom-platform
automountServiceAccountToken: false
